DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_info;
DROP TABLE IF EXISTS user_matrix;
DROP TABLE IF EXISTS user_days;
DROP TABLE IF EXISTS user_equipment;
DROP TABLE IF EXISTS workout_data;
DROP TABLE IF EXISTS workout_matrix;
DROP TABLE IF EXISTS workout_equipment;
DROP TABLE IF EXISTS exercise_data;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE user_info (
  user_id INTEGER NOT NULL,
  body_weight REAL NOT NULL,
  height REAL NOT NULL,
  daily_rate REAL NOT NULL,
  experience REAL NOT NULL,
  A REAL NOT NULL DEFAULT 65,
  B REAL NOT NULL DEFAULT 631000,
  C REAL NOT NULL DEFAULT 40,
  I REAL NOT NULL DEFAULT 10.0,
  k REAL NOT NULL,
  goal TEXT,
  work_time INTEGER NOT NULL DEFAULT 60,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE user_matrix (
  user_id INTEGER NOT NULL,
  a INTEGER NOT NULL DEFAULT 1,
  b INTEGER NOT NULL DEFAULT 1,
  c INTEGER NOT NULL DEFAULT 1,
  d INTEGER NOT NULL DEFAULT 1,
  e INTEGER NOT NULL DEFAULT 1,
  f INTEGER NOT NULL DEFAULT 1,
  g INTEGER NOT NULL DEFAULT 1,
  h INTEGER NOT NULL DEFAULT 1,
  i INTEGER NOT NULL DEFAULT 1,
  j INTEGER NOT NULL DEFAULT 1,
  k INTEGER NOT NULL DEFAULT 1,
  l INTEGER NOT NULL DEFAULT 1,
  m INTEGER NOT NULL DEFAULT 1,
  n INTEGER NOT NULL DEFAULT 1,
  o INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE user_days (
  user_id INTEGER NOT NULL,
  week_day TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE user_equipment (
  user_id INTEGER NOT NULL,
  equipment TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE workout_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    time INTEGER NOT NULL,
    intensity REAL NOT NULL,
    goal TEXT NOT NULL,
    volume INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE workout_matrix (
  workout_data_id INTEGER NOT NULL,
  a REAL NOT NULL DEFAULT 1,
  b REAL NOT NULL DEFAULT 1,
  c REAL NOT NULL DEFAULT 1,
  d REAL NOT NULL DEFAULT 1,
  e REAL NOT NULL DEFAULT 1,
  f REAL NOT NULL DEFAULT 1,
  g REAL NOT NULL DEFAULT 1,
  h REAL NOT NULL DEFAULT 1,
  i REAL NOT NULL DEFAULT 1,
  j REAL NOT NULL DEFAULT 1,
  k REAL NOT NULL DEFAULT 1,
  l REAL NOT NULL DEFAULT 1,
  m REAL NOT NULL DEFAULT 1,
  n REAL NOT NULL DEFAULT 1,
  o REAL NOT NULL DEFAULT 1,
  FOREIGN KEY (workout_data_id) REFERENCES workout_data(id)
);

CREATE TABLE workout_equipment (
  workout_data_id INTEGER NOT NULL,
  equipment TEXT NOT NULL,
  FOREIGN KEY (workout_data_id) REFERENCES workout_data(id)
);

CREATE TABLE exercise_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    workout_data_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    time INTEGER NOT NULL,
    intensity REAL NOT NULL,
    weight INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    rating REAL NOT NULL,
    volume INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id),
    FOREIGN KEY (workout_data_id) REFERENCES workout_data(id)
);